"""add extended metrics columns

Revision ID: edd825e38250
Revises: 9ed8ea2079a7
Create Date: 2026-02-11 20:19:05.891309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd825e38250'
down_revision: Union[str, None] = '9ed8ea2079a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('sortino_ratio', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('profit_factor', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('avg_trade_duration', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('max_consecutive_losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'max_consecutive_losses')
    op.drop_column('backtests', 'avg_trade_duration')
    op.drop_column('backtests', 'profit_factor')
    op.drop_column('backtests', 'sortino_ratio')
    # ### end Alembic commands ###
